homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 509
  unit_system: metric
  time_zone: Europe/Berlin

  customize: !include customizations.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
  purge_days: 3

# Track the sun
sun:

# Enable Z-Wave
zwave:
  usb_path: /dev/zstick

# Add media players
media_player:
  - platform: sonos