homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 509
  unit_system: metric
  time_zone: Europe/Berlin

  customize: !include misc/customizations.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
  purge_days: 3

# Track the sun
sun:

# Enable Z-Wave
zwave:
  usb_path: /dev/zstick

# Apple iOS:
ios:

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

# Add media players
media_player:
  - platform: sonos

remote:
  - platform: harmony
    name: Harmony
    host: harmonyhub

emulated_hue:
  expose_by_default: false

tts:
  - platform: google
    language: de

script: !include_dir_named scripts/
automation: !include_dir_list automations/
input_select: !include misc/input_selects.yaml