alias: Harmony - power off from input select
trigger:
  platform: state
  entity_id: input_select.harmony
  to: 'Aus'
condition:
  condition: template
  value_template: '{{ states.remote.harmony.attributes.current_activity != "PowerOff" }}'
action:
  service: remote.turn_off
  entity_id: remote.harmony
