alias: Harmony - start activity from input select
trigger:
  platform: state
  entity_id: input_select.harmony
condition:
  condition: template
  value_template: '{{ states.remote.harmony.attributes.current_activity != states.input_select.harmony.state and not is_state("input_select.harmony", "Aus") }}'
action:
  service: remote.turn_on
  entity_id: remote.harmony
  data_template:
    activity: >
      {% if is_state("input_select.harmony", "Apple TV sehen") %}
        14431475
      {% elif is_state("input_select.harmony", "Fernsehen") %}
        14431436
      {% elif is_state("input_select.harmony", "Wiedergabe PS3") %}
        14431521
      {% elif is_state("input_select.harmony", "Musik hören") %}
        14431578
      {% elif is_state("input_select.harmony", "Spotify") %}
        16371284
      {% elif is_state("input_select.harmony", "iPod hören") %}
        14431550
      {% elif is_state("input_select.harmony", "Fire TV sehen") %}
        14431499
      {% endif %}